<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	</PropertyGroup>

</Project>